# Generated by Django 4.0 on 2025-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=5, help_text='Estimated time to read the post (in minutes)'),
        ),
    ]
