# Generated by Django 4.0 on 2025-11-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='default-icon', max_length=50),
        ),
    ]
