# Generated by Django 5.2.8 on 2025-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="URL-friendly version of the name",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="URL-friendly version of the title",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="URL-friendly version of the name",
                unique=True,
            ),
        ),
    ]
