# Generated by Django 5.2.8 on 2025-11-22 21:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_category_slug_alter_post_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(help_text="Main content of the post"),
        ),
    ]
