# Generated by Django 5.2.8 on 2025-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="Main content of the post"),
        ),
    ]
